# Terminal multiplexer
brew "tmux"
# Command-line interface for 1Password
cask "1password-cli"
# Terminal emulator that uses platform-native UI and GPU acceleration
cask "ghostty"
go "cmd/go"
go "cmd/gofmt"
npm "corepack"
# Pack, ship and run any application as a lightweight container
brew "docker"
# Container runtimes on MacOS (and Linux) with minimal setup
brew "colima"
