# Terminal multiplexer
brew "tmux"
# Command-line interface for 1Password
cask "1password-cli"
# Terminal emulator that uses platform-native UI and GPU acceleration
cask "ghostty"
go "cmd/go"
go "cmd/gofmt"
npm "corepack"
