[tools]
fzf = "latest"
"github:cli/cli" = "latest"
"github:dandavison/delta" = "latest"
"github:jj-vcs/jj" = "latest"
"github:sharkdp/bat" = "latest"
"github:sharkdp/fd" = "latest"
"github:twpayne/chezmoi" = "latest"
go = "latest"
jq = "latest"
jqp = "latest"
neovim = "latest"
zoxide = "latest"
