[tools]
claude-code = "latest"
fzf = "latest"
"github:cli/cli" = "latest"
"github:dandavison/delta" = "latest"
"github:jj-vcs/jj" = "latest"
"github:morantron/tmux-fingers" = "latest"
"github:rtk-ai/rtk" = "latest"
"github:sharkdp/bat" = "latest"
"github:sharkdp/fd" = "latest"
"github:twpayne/chezmoi" = "latest"
glab = "latest"
glow = "latest"
go = "latest"
jq = "latest"
jqp = "latest"
neovim = "latest"
node = "lts"
"npm:@colbymchenry/codegraph" = "latest"
nushell = "latest"
rg = "latest"
uv = "latest"
zoxide = "latest"
